### PR TITLE
Add XML files for dEQP feature flags

### PR DESCRIPTION
**Pull request by brunorolak**
Add XML files for the new android.software.opengles.deqp.level feature
flag, and for the latest version of the
android.software.vulkan.deqp.level feature flag.

Bug: 159842117
Change-Id: Ia6256254e8cdb3573f6c3ad99a760e7db1c5d15e

### CODE REVIEW

**Comment by brunorolak** [comment]
just to add openGL support

**Comment by xNombre** [comment]
Why is it needed in 11.0?

**Comment by brunorolak** [comment]
Cos areldy has I'm A12, but I still building and supo A11, and generates a error when build.

**Comment by xNombre** [comment]
Lol no, I wont add it just because youre too lazy to opt it out for a11 build

**Comment by brunorolak** [comment]
Bro I'm not lazzy, my device needs 5 hacks in source to boot up Android 12 :/ I tries a lots of things to fix A12 but no way for my potato phone for now.

**Pull request closed without merging**
