### PR TITLE
RenderEngine: Set blur filter shader version from 3.1 to 3.0

### PR DESCRIPTION
**Pull request by koron393**
* Old device (like msm8974) does not support OpenGL ES 3.1
  So set shader version to 3.0

Test: build
Test: adb shell setprop debug.sf.disableBlurs 0
Test: adb shell setprop ro.surface_flinger.supports_background_blur 1
Signed-off-by: koron393 <koron393@gmail.com>
Change-Id: I7e2d401bb895b0d2dc4dc307eed285a4d86dbff1

### CODE REVIEW

**Comment by Khalvat-M** [comment]
+1 now blur working fine in my s4 and s5 msm8974

**Comment by xNombre** [comment]
I think it was defined v310 for some reason... and Im not a fan of this crufty change.
Firstly you should try setting ro.opengles.version to 196610. S4 was updated to Android 5.0 which /should/ support OpenGL 3.1 according to this https://developer.android.com/guide/topics/graphics/opengl
If it fails then try to update your blobs.

As a last resort we could introduce flag for legacy devices to change this. Setting 300 as default ver for all devices is a big question mark and could lead to some magical unexpected issues.

**Comment by neobuddy89** [comment]
Please add a build flag. So that newer devices are not affected or not forced to use old version.
Example
https://github.com/LineageOS/android_frameworks_native/commit/8b1c75626431309213492f442b5c766298dd6974

**Comment by neobuddy89** [comment]
and resubmit pull request as code base is rebased.

**Comment by Khalvat-M** [comment]
https://gerrit.aicp-rom.com/c/AICP/frameworks_native/+/105646

Is it possible merge this instead??

**Comment by gwolf2u** [comment]
Submit PR

**Comment by neobuddy89** [comment]
> https://gerrit.aicp-rom.com/c/AICP/frameworks_native/+/105646
> 
> Is it possible merge this instead??

added

**Pull request closed without merging**
