### PR TITLE
Cast Fix #2

### PR DESCRIPTION
**Pull request by amanrajOO7**

### CODE REVIEW

**Comment by neobuddy89** [comment]
What's this? Commit and its revert?

**Comment by amanrajOO7** [comment]
There are too many commits after this so this commit overridden & that why I've reverted & again picked this commit to fix sound in miracast

**Comment by neobuddy89** [comment]
Where are other commits? I dont see any.

**Comment by amanrajOO7** [comment]
Check changes in this repo committed after the Input Priority commit.

**Comment by amanrajOO7** [comment]
Some of the change committed after this have overridden it because I've compiled build without it & got no sound while cast & with revert & commit it's fixed.

**Comment by neobuddy89** [comment]
There are only 2 commits in this pull request.
Where are rest of commits ?

**Pull request closed without merging**
